//
//  Ratings.swift
//  Advocate
//
//  Created by David Oliver Doswell on 3/29/18.
//  Copyright © 2018 David Oliver Doswell. All rights reserved.
//

import UIKit

struct Restaurant {
    let acorn = "Acorn"
    let bakersfield = "Bakersfield"
    let banhMiAndTi = "Banh Mi & Ti"
    let barMarco = "Bar Marco"
    let bdsMongolianGrill = "BD's MongolianGrill"
    let bruneaux = "Bruneaux"
    let burghers = "Burgh’ers"
    let burgatory = "Burgatory"
    let butcherAndTheRye = "Butcher and The Rye"
    let cambodican = "Cambodican"
    let carmiFamilyRestaurant = "Carmi Family Restaurant"
    let cityWorks = "City Works"
    let colombianSpot = "Colombian Spot"
    let condado = "Condado"
    let cornerMercantile = "Corner Mercantile"
    let cure = "Cure"
    let theCommoner = "The Commoner"
    let dinette = "Dinette"
    let doubleWideGrill = "Double Wide Grill"
    let e2 = "E2"
    let elBurro = "El Burro"
    let emporioMeatBall = "Emporio: A Meatball Joint"
    let eddieVs = "Eddie V's"
    let eden = "Eden"
    let federalGalley = "Federal Galley"
    let fl2 = "fl.2 (Floor 2)"
    let thefoundryTableAndTap = "The Foundry Table and Tap"
    let gauchoParilla = "Gaucho Parilla"
    let glutenFreeGoatBakery = "Gluten Free Goat Bakery & Cafe"
    let honeygrow = "Honeygrow"
    let ineffableCaPhe = "Ineffable Ca Phe"
    let jeromeBettisGrille = "Jerome Bettis Grille"
    let kiPollo = "Ki Pollo"
    let kiRamen = "Ki Ramen"
    let lagourmandine = "La Gourmandine"
    let legumeBistro = "Legume Bistro"
    let leLyonnais  = "Le Lyonnais"
    let lili = "Lili"
    let local = "Local"
    let luncheonette = "Luncheonette"
    let meatAndPotatoes = "Meat and Potatoes"
    let theMerchantOysterCo = "The Merchant Oyster Co"
    let theMintt = "The Mintt"
    let montereyPub = "Monterey Pub"
    let morcilla = "Morcilla"
    let mortonsSteakhouse = "Morton's Steakhouse"
    let nickysThaiKitchen = "Nicky's Thai Kitchen"
    let nineOnNine = "Nine On Nine"
    let noodleHead = "NoodleHead"
    let onionMaiden = "Onion Maiden"
    let orTheWhale = "OrTheWhale"
    let overTheBarCafe = "Over The Bar Cafe"
    let pandgPamelasDiner = "P&G Pamela's Diner"
    let paris66 = "Paris 66"
    let peoplesIndianRestaurant = "People's Indian Restaurant"
    let piccoloForno = "Piccolo Forna"
    let pittsburghPoke = "Pittsburgh Poke"
    let plumPanAsianKitchen = "Plum Pan Asian Kitchen"
    let primantiBros = "Primamti Brothers"
    let pusadeesGarden = "Pusadee's Garden"
    let ramenBar = "Ramen Bar"
    let redTheSteakhouse = "Red, The Steakhouse"
    let ruthsChris = "Ruth's Chris"
    let scoglios = "Scoglio's"
    let seviche = "Seviche"
    let smokeBBQTaqueria = "Smoke BBQ Taqueria"
    let soba = "Soba"
    let socialHouse = "Social House"
    let spakBros = "Spak Bros."
    let spoon = "Spoon"
    let spork = "Spork"
    let stagionis = "Stagioni's"
    let station = "Station"
    let steelCactus = "Steel Cactus"
    let stuffdPierogieBar = "Stuff’d Pierogie Bar"
    let subba = "Subba"
    let superiorMotors = "Superior Motors"
    let talia = "Talia"
    let tako = "Täko"
    let tajmahal = "Taj Mahal"
    let tamarind = "Tamarind"
    let tambellinnis = "Tambellinni's"
    let tasteOfIndia = "Taste of India"
    let theTwistedFrenchman = "The Twisted Frenchman"
    let threadbareCiderhouseAndMeadery = "Threadbare Ciderhouse and Meadery"
    let umami = "Umami"
    let umi = "Umi"
    let unionStandard = "Union Standard"
    let urbanTap = "Urban Tap"
    let waiwai = "Wai Wai"
    let yard = "Yard"
    let yuzuKitchen = "Yuzu Kitchen"
    let zenith = "Zenith"
}

struct RestaurantGrade {
    let aGrade = "A"
    let bGrade = "B"
    let cGrade = "C"
    let dGrade = "D"
    let fGrade = "F"
    
    let aMinusGrade = "A-"
    let bMinusGrade = "B-"
    let cMinusGrade = "C-"
    let dMinusGrade = "D-"
}

struct RestaurantGradeLabel {
    let aGradeLabel = "Exceptional"
    let aMinusGradeLabel = "Premium"
    let bGradelabel = "Solid"
    let bMinusGradeLabel = "Okay"
    let cGradeLabel = "Average"
    let cMinusGradeLabel = "Sketchy"
    let dGradeLabel = "Bad"
    let dMinusGradeLabel = "Sucks"
    let fGradeLabel = "Awful"
}
